<?php

defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . '/libraries/REST_Controller.php';

class Parameters extends REST_Controller
{

    function __construct()
    {

        parent::__construct();
        $this->load->model('workshop/parameters_model');
    }

    public function index_get()
    {
        //Get params
        $company_id = (int)$this->get('company_id');

        log_message("debug", "*********** index_get start company_id {$company_id} ***********");

        $result = $this->parameters_model->get_all_parameters($company_id);

        $this->response([
            'response' => $result,
            'status' => TRUE,
            'description' => 'To get all [/workshop/Parameters/company_id/] or to get single [/workshop/Parameters/find/item_id]'
        ], REST_Controller::HTTP_OK);

    }

    public function find_get()
    {
        $item_id = (int)$this->get('item_id');

        log_message("debug", "*********** find_get start group_id {$item_id} ***********");

        $result = $this->parameters_model->get_single_parameter("", $item_id);

        $this->response([
            'response' => $result,
            'status' => TRUE,
            'description' => 'To get all [/workshop/parameter/group_id/] or to get single [/workshop/parameter/find/group_id]'
        ], REST_Controller::HTTP_OK);
    }

    public function index_put()
    {

        log_message("debug", "*********** index_put start ***********");

        $data = array(
            'company_id' => $this->put('company_id'),
            'item_name' => $this->put('item_name'),
        );

        log_message("debug", "Getting ready to insert... " . json_encode($data));

        if (empty($data['item_name'])) {

            log_message("debug", "index_put Trying to insert empty parameter name... ");

            return $this->response([
                'status' => FALSE,
                'message' => 'Trying to create empty parameter name',
                'description' => 'create item put/ {company_id,item_name} name cannot be null'
            ], REST_Controller::HTTP_BAD_REQUEST);
        }

        if ($this->parameters_model->parameter_exists($data['item_name'], $data['company_id']) == TRUE) {

            log_message("debug", "index_put Trying to duplicate a parameter name... ");

            return $this->response([
                'response' => $data,
                'status' => FALSE,
                'message' => 'Trying to duplicate a parameter name',
                'description' => 'create group put/ {company_id,item_name} name cannot be null'
            ], REST_Controller::HTTP_BAD_REQUEST);
        }

        $response = $this->parameters_model->create_parameter($data);

        if ($response == FALSE) {

            log_message("debug", "index_put Database refused. Try again!... ");

            return $this->response([
                'response' => $data,
                'status' => FALSE,
                'message' => 'Database refused. Try again!',
                'description' => 'create parameter put/ {company_id,item_name} name cannot be null'
            ], REST_Controller::HTTP_INTERNAL_SERVER_ERROR);
        }

        log_message("debug", "index_put Record created!... ");

        return $this->response([
            'response' => $response,
            'status' => true,
            'message' => 'parameter created!',
            'description' => 'To get all [workshop/parameter/company_id/] or to get single [workshop/parameter/find/group_id]'
        ], REST_Controller::HTTP_CREATED);
    }

    public function index_post()
    {
        $data = [
            'item_id' => $this->post('item_id'), // Automatically generated by the model
            'item_name' => $this->post('item_name'),
        ];

        if (empty($data['item_id']) || empty($data['item_name'])) {

            log_message("debug", "index_post Empty item_id/item_name supplied... ");

            return $this->response([
                'response' => $data,
                'status' => FALSE,
                'message' => 'Empty item_id/item_name supplied',
                'description' => 'Update group post/ {group_id,item_name} name and id cannot be null'
            ], REST_Controller::HTTP_BAD_REQUEST);
        }

        if ($this->parameters_model->parameter_id_exists($data['item_id']) != TRUE) {

            log_message("debug", "index_POST Record does not exist... ");

            return $this->response([
                'response' => $data,
                'status' => FALSE,
                'message' => 'This parameter you are trying to update does not exist',
                'description' => 'create item put/ {company_id,item_name} name cannot be null'
            ], REST_Controller::HTTP_BAD_REQUEST);
        }

        $response = $this->parameters_model->update_parameter($data);

        if ($response == FALSE) {

            return $this->response([
                'response' => $data,
                'status' => FALSE,
                'message' => 'Database refused. Try again!',
                'description' => 'create parameter put/ {company_id,item_name} name cannot be null'
            ], REST_Controller::HTTP_INTERNAL_SERVER_ERROR);
        }

        log_message("debug", "Parameter Updated...");

        return $this->response([
            'response' => $response,
            'status' => TRUE,
            'message' => 'parameter Updated!',
            'description' => 'To get all [workshop/groups/company_id/] or to get single [/workshop/groups/find/department_id]'
        ], REST_Controller::HTTP_OK);

    }

    public function remove_post()
    {
        $data = [
            'item_id' => $this->post('item_id'), // Automatically generated by the model
        ];

        log_message("debug", "Getting ready to remove... " . json_encode($data));


        $response = $this->parameters_model->delete_parameter($data);

        if ($response == FALSE) {

            return $this->response([
                'response' => $data,
                'status' => FALSE,
                'message' => 'Database refused. Try again!',
                'description' => 'create parameter put/ {company_id,item_name} name cannot be null'
            ], REST_Controller::HTTP_INTERNAL_SERVER_ERROR);
        }

        log_message("debug", "Parameter Updated...");

        return $this->response([
            'response' => $response,
            'status' => TRUE,
            'message' => 'parameters Removed!',
            'description' => 'To get all [workshop/groups/company_id/] or to get single [/workshop/groups/find/department_id]'
        ], REST_Controller::HTTP_OK);
    }
}